/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTasksIndexRouteImport } from './routes/_authed/tasks/index'
import { Route as AuthedSessionsIndexRouteImport } from './routes/_authed/sessions/index'
import { Route as AuthedPromptsIndexRouteImport } from './routes/_authed/prompts/index'
import { Route as AuthedPlansIndexRouteImport } from './routes/_authed/plans/index'
import { Route as AuthedTasksTaskIdRouteImport } from './routes/_authed/tasks/$taskId'
import { Route as AuthedPlansPlanIdRouteImport } from './routes/_authed/plans/$planId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTasksIndexRoute = AuthedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionsIndexRoute = AuthedSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPromptsIndexRoute = AuthedPromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansIndexRoute = AuthedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTasksTaskIdRoute = AuthedTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansPlanIdRoute = AuthedPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plans/$planId': typeof AuthedPlansPlanIdRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/plans/': typeof AuthedPlansIndexRoute
  '/prompts/': typeof AuthedPromptsIndexRoute
  '/sessions/': typeof AuthedSessionsIndexRoute
  '/tasks/': typeof AuthedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/plans/$planId': typeof AuthedPlansPlanIdRoute
  '/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/plans': typeof AuthedPlansIndexRoute
  '/prompts': typeof AuthedPromptsIndexRoute
  '/sessions': typeof AuthedSessionsIndexRoute
  '/tasks': typeof AuthedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/plans/$planId': typeof AuthedPlansPlanIdRoute
  '/_authed/tasks/$taskId': typeof AuthedTasksTaskIdRoute
  '/_authed/plans/': typeof AuthedPlansIndexRoute
  '/_authed/prompts/': typeof AuthedPromptsIndexRoute
  '/_authed/sessions/': typeof AuthedSessionsIndexRoute
  '/_authed/tasks/': typeof AuthedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/plans/$planId'
    | '/tasks/$taskId'
    | '/plans/'
    | '/prompts/'
    | '/sessions/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/plans/$planId'
    | '/tasks/$taskId'
    | '/plans'
    | '/prompts'
    | '/sessions'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/plans/$planId'
    | '/_authed/tasks/$taskId'
    | '/_authed/plans/'
    | '/_authed/prompts/'
    | '/_authed/sessions/'
    | '/_authed/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/tasks/': {
      id: '/_authed/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthedTasksIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sessions/': {
      id: '/_authed/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthedSessionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/prompts/': {
      id: '/_authed/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof AuthedPromptsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/': {
      id: '/_authed/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthedPlansIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tasks/$taskId': {
      id: '/_authed/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AuthedTasksTaskIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans/$planId': {
      id: '/_authed/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AuthedPlansPlanIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedPlansPlanIdRoute: typeof AuthedPlansPlanIdRoute
  AuthedTasksTaskIdRoute: typeof AuthedTasksTaskIdRoute
  AuthedPlansIndexRoute: typeof AuthedPlansIndexRoute
  AuthedPromptsIndexRoute: typeof AuthedPromptsIndexRoute
  AuthedSessionsIndexRoute: typeof AuthedSessionsIndexRoute
  AuthedTasksIndexRoute: typeof AuthedTasksIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPlansPlanIdRoute: AuthedPlansPlanIdRoute,
  AuthedTasksTaskIdRoute: AuthedTasksTaskIdRoute,
  AuthedPlansIndexRoute: AuthedPlansIndexRoute,
  AuthedPromptsIndexRoute: AuthedPromptsIndexRoute,
  AuthedSessionsIndexRoute: AuthedSessionsIndexRoute,
  AuthedTasksIndexRoute: AuthedTasksIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
